name: our_story
description: "An interactive story app with AI-generated content"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # UI components
  cupertino_icons: ^1.0.8
  file_picker: ^8.3.7
  flutter_chat_ui: ^1.6.15
  flutter_link_previewer: ^3.2.2
  url_launcher: ^6.2.5

  # Storage
  shared_preferences: ^2.2.3

  # Sharing
  share_plus: ^10.1.2

  # AI service
  google_generative_ai: ^0.4.6
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: false

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Regular.ttf
        - asset: assets/fonts/Cinzel-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cinzel-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cinzel-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cinzel-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cinzel-Black.ttf
          weight: 900